//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.TaskPlanner
{
    [Serializable]
    public class PlanPickPlaceFeedback : Message
    {
        public const string k_RosMessageName = "task_planner/PlanPickPlace";
        public override string RosMessageName => k_RosMessageName;

        public string feedback;

        public PlanPickPlaceFeedback()
        {
            this.feedback = "";
        }

        public PlanPickPlaceFeedback(string feedback)
        {
            this.feedback = feedback;
        }

        public static PlanPickPlaceFeedback Deserialize(MessageDeserializer deserializer) => new PlanPickPlaceFeedback(deserializer);

        private PlanPickPlaceFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.feedback);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.feedback);
        }

        public override string ToString()
        {
            return "PlanPickPlaceFeedback: " +
            "\nfeedback: " + feedback.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
