//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.SceneHandler
{
    [Serializable]
    public class SceneObjectsMsg : Message
    {
        public const string k_RosMessageName = "scene_handler/SceneObjects";
        public override string RosMessageName => k_RosMessageName;

        public SceneObjectMsg[] objects;

        public SceneObjectsMsg()
        {
            this.objects = new SceneObjectMsg[0];
        }

        public SceneObjectsMsg(SceneObjectMsg[] objects)
        {
            this.objects = objects;
        }

        public static SceneObjectsMsg Deserialize(MessageDeserializer deserializer) => new SceneObjectsMsg(deserializer);

        private SceneObjectsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.objects, SceneObjectMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.objects);
            serializer.Write(this.objects);
        }

        public override string ToString()
        {
            return "SceneObjectsMsg: " +
            "\nobjects: " + System.String.Join(", ", objects.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
