//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MoveitTaskConstructor
{
    [Serializable]
    public class ExecuteTaskSolutionFeedback : Message
    {
        public const string k_RosMessageName = "moveit_task_constructor_msgs/ExecuteTaskSolution";
        public override string RosMessageName => k_RosMessageName;

        //  finished subtrajectory id / number
        public uint sub_id;
        public uint sub_no;

        public ExecuteTaskSolutionFeedback()
        {
            this.sub_id = 0;
            this.sub_no = 0;
        }

        public ExecuteTaskSolutionFeedback(uint sub_id, uint sub_no)
        {
            this.sub_id = sub_id;
            this.sub_no = sub_no;
        }

        public static ExecuteTaskSolutionFeedback Deserialize(MessageDeserializer deserializer) => new ExecuteTaskSolutionFeedback(deserializer);

        private ExecuteTaskSolutionFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.sub_id);
            deserializer.Read(out this.sub_no);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.sub_id);
            serializer.Write(this.sub_no);
        }

        public override string ToString()
        {
            return "ExecuteTaskSolutionFeedback: " +
            "\nsub_id: " + sub_id.ToString() +
            "\nsub_no: " + sub_no.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
