//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MoveitTaskConstructor
{
    [Serializable]
    public class ExecuteTaskSolutionResult : Message
    {
        public const string k_RosMessageName = "moveit_task_constructor_msgs/ExecuteTaskSolution";
        public override string RosMessageName => k_RosMessageName;

        //  result of execution
        public Moveit.MoveItErrorCodesMsg error_code;

        public ExecuteTaskSolutionResult()
        {
            this.error_code = new Moveit.MoveItErrorCodesMsg();
        }

        public ExecuteTaskSolutionResult(Moveit.MoveItErrorCodesMsg error_code)
        {
            this.error_code = error_code;
        }

        public static ExecuteTaskSolutionResult Deserialize(MessageDeserializer deserializer) => new ExecuteTaskSolutionResult(deserializer);

        private ExecuteTaskSolutionResult(MessageDeserializer deserializer)
        {
            this.error_code = Moveit.MoveItErrorCodesMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.error_code);
        }

        public override string ToString()
        {
            return "ExecuteTaskSolutionResult: " +
            "\nerror_code: " + error_code.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
