//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MoveitTaskConstructor
{
    [Serializable]
    public class ExecuteTaskSolutionGoal : Message
    {
        public const string k_RosMessageName = "moveit_task_constructor_msgs/ExecuteTaskSolution";
        public override string RosMessageName => k_RosMessageName;

        //  Task solution to execute
        public SolutionMsg solution;

        public ExecuteTaskSolutionGoal()
        {
            this.solution = new SolutionMsg();
        }

        public ExecuteTaskSolutionGoal(SolutionMsg solution)
        {
            this.solution = solution;
        }

        public static ExecuteTaskSolutionGoal Deserialize(MessageDeserializer deserializer) => new ExecuteTaskSolutionGoal(deserializer);

        private ExecuteTaskSolutionGoal(MessageDeserializer deserializer)
        {
            this.solution = SolutionMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.solution);
        }

        public override string ToString()
        {
            return "ExecuteTaskSolutionGoal: " +
            "\nsolution: " + solution.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
