//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MoveitTaskConstructor
{
    [Serializable]
    public class GetSolutionResponse : Message
    {
        public const string k_RosMessageName = "moveit_task_constructor_msgs/GetSolution";
        public override string RosMessageName => k_RosMessageName;

        public SolutionMsg solution;

        public GetSolutionResponse()
        {
            this.solution = new SolutionMsg();
        }

        public GetSolutionResponse(SolutionMsg solution)
        {
            this.solution = solution;
        }

        public static GetSolutionResponse Deserialize(MessageDeserializer deserializer) => new GetSolutionResponse(deserializer);

        private GetSolutionResponse(MessageDeserializer deserializer)
        {
            this.solution = SolutionMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.solution);
        }

        public override string ToString()
        {
            return "GetSolutionResponse: " +
            "\nsolution: " + solution.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
