//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MoveitTaskConstructor
{
    [Serializable]
    public class GetSolutionRequest : Message
    {
        public const string k_RosMessageName = "moveit_task_constructor_msgs/GetSolution";
        public override string RosMessageName => k_RosMessageName;

        //  ID of solution (as published in Task msg)
        public uint solution_id;

        public GetSolutionRequest()
        {
            this.solution_id = 0;
        }

        public GetSolutionRequest(uint solution_id)
        {
            this.solution_id = solution_id;
        }

        public static GetSolutionRequest Deserialize(MessageDeserializer deserializer) => new GetSolutionRequest(deserializer);

        private GetSolutionRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.solution_id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.solution_id);
        }

        public override string ToString()
        {
            return "GetSolutionRequest: " +
            "\nsolution_id: " + solution_id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
