//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MoveitTaskConstructor
{
    [Serializable]
    public class PropertyMsg : Message
    {
        public const string k_RosMessageName = "moveit_task_constructor_msgs/Property";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        public string description;
        public string type;
        public string value;

        public PropertyMsg()
        {
            this.name = "";
            this.description = "";
            this.type = "";
            this.value = "";
        }

        public PropertyMsg(string name, string description, string type, string value)
        {
            this.name = name;
            this.description = description;
            this.type = type;
            this.value = value;
        }

        public static PropertyMsg Deserialize(MessageDeserializer deserializer) => new PropertyMsg(deserializer);

        private PropertyMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.description);
            deserializer.Read(out this.type);
            deserializer.Read(out this.value);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.description);
            serializer.Write(this.type);
            serializer.Write(this.value);
        }

        public override string ToString()
        {
            return "PropertyMsg: " +
            "\nname: " + name.ToString() +
            "\ndescription: " + description.ToString() +
            "\ntype: " + type.ToString() +
            "\nvalue: " + value.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
