//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MoveitTaskConstructor
{
    [Serializable]
    public class StageDescriptionMsg : Message
    {
        public const string k_RosMessageName = "moveit_task_constructor_msgs/StageDescription";
        public override string RosMessageName => k_RosMessageName;

        //  static description of a stage
        //  unique id within task
        public uint id;
        //  parent id, parent_id == id means root
        public uint parent_id;
        //  name of this stage
        public string name;
        //  flags: interface, ...
        public uint flags;
        //  properties
        public PropertyMsg[] properties;

        public StageDescriptionMsg()
        {
            this.id = 0;
            this.parent_id = 0;
            this.name = "";
            this.flags = 0;
            this.properties = new PropertyMsg[0];
        }

        public StageDescriptionMsg(uint id, uint parent_id, string name, uint flags, PropertyMsg[] properties)
        {
            this.id = id;
            this.parent_id = parent_id;
            this.name = name;
            this.flags = flags;
            this.properties = properties;
        }

        public static StageDescriptionMsg Deserialize(MessageDeserializer deserializer) => new StageDescriptionMsg(deserializer);

        private StageDescriptionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.parent_id);
            deserializer.Read(out this.name);
            deserializer.Read(out this.flags);
            deserializer.Read(out this.properties, PropertyMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.parent_id);
            serializer.Write(this.name);
            serializer.Write(this.flags);
            serializer.WriteLength(this.properties);
            serializer.Write(this.properties);
        }

        public override string ToString()
        {
            return "StageDescriptionMsg: " +
            "\nid: " + id.ToString() +
            "\nparent_id: " + parent_id.ToString() +
            "\nname: " + name.ToString() +
            "\nflags: " + flags.ToString() +
            "\nproperties: " + System.String.Join(", ", properties.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
