//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MoveitTaskConstructor
{
    [Serializable]
    public class SubSolutionMsg : Message
    {
        public const string k_RosMessageName = "moveit_task_constructor_msgs/SubSolution";
        public override string RosMessageName => k_RosMessageName;

        //  generic solution information
        public SolutionInfoMsg info;
        //  IDs of subsolutions
        public uint[] sub_solution_id;

        public SubSolutionMsg()
        {
            this.info = new SolutionInfoMsg();
            this.sub_solution_id = new uint[0];
        }

        public SubSolutionMsg(SolutionInfoMsg info, uint[] sub_solution_id)
        {
            this.info = info;
            this.sub_solution_id = sub_solution_id;
        }

        public static SubSolutionMsg Deserialize(MessageDeserializer deserializer) => new SubSolutionMsg(deserializer);

        private SubSolutionMsg(MessageDeserializer deserializer)
        {
            this.info = SolutionInfoMsg.Deserialize(deserializer);
            deserializer.Read(out this.sub_solution_id, sizeof(uint), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.info);
            serializer.WriteLength(this.sub_solution_id);
            serializer.Write(this.sub_solution_id);
        }

        public override string ToString()
        {
            return "SubSolutionMsg: " +
            "\ninfo: " + info.ToString() +
            "\nsub_solution_id: " + System.String.Join(", ", sub_solution_id.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
