//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MoveitTaskConstructor
{
    [Serializable]
    public class TaskStatisticsMsg : Message
    {
        public const string k_RosMessageName = "moveit_task_constructor_msgs/TaskStatistics";
        public override string RosMessageName => k_RosMessageName;

        //  unique id of generating task
        public string task_id;
        //  list of all stages, including the task stage itself
        public StageStatisticsMsg[] stages;

        public TaskStatisticsMsg()
        {
            this.task_id = "";
            this.stages = new StageStatisticsMsg[0];
        }

        public TaskStatisticsMsg(string task_id, StageStatisticsMsg[] stages)
        {
            this.task_id = task_id;
            this.stages = stages;
        }

        public static TaskStatisticsMsg Deserialize(MessageDeserializer deserializer) => new TaskStatisticsMsg(deserializer);

        private TaskStatisticsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.task_id);
            deserializer.Read(out this.stages, StageStatisticsMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.task_id);
            serializer.WriteLength(this.stages);
            serializer.Write(this.stages);
        }

        public override string ToString()
        {
            return "TaskStatisticsMsg: " +
            "\ntask_id: " + task_id.ToString() +
            "\nstages: " + System.String.Join(", ", stages.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
